export const structSettings = {
  configs: {
    autoTuning: true,
    decimals: 2,
    fontsize: 16,
    language: 'en',
    theme: 'auto',
    tuning: 440,
    minFreq: 32,
    maxFreq: 7902,
    profile: 'bgate',
    tick_tone_start: 555,
    tick_tone: 440,
    tick_volume: 0.5,
    beats: 4,
  },
  files: {
    autoupdate: true,
    filename: '',
    filesize: 0,
    duration: null,
    keyData: null,
    measures: null,
    tempo: null,
    sampleRate: null,
    history: [],
  },
  milliseconds: {
    autoupdate_tap: true,
    predelay: 0,
    slide: 1,
    swing: 0,
    tempo: 120,
    tap_volume: 0.8,
    tap_volume_last: 0.8,
  },
  reference: {
    gainMatch: true,
    muted: false,
    volume: 10,
  },
  scales: {
    key: {
      value: 'C',
      text: 'C',
    },
    name: {
      value: 'major',
      text: 'Major',
    },
    octave: '5',
  },
  section: 'milliseconds',
}
